import { Inter } from "next/font/google";
import "./globals.css";
import Appbar from "./Components/Appbar";
import {Providers} from "./provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "DCEX",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Providers>
      <Appbar/>
      {children}
      </Providers>
      </body>
    </html>
  );
}
